<img src='tensor.png'>

<img src='parcs.png'>

In [2]:
import tensorflow as tf
from tensorflow import keras
import numpy as np

In [3]:
fashion_mnist = keras.datasets.fashion_mnist

(train_images, train_labels), (test_images, test_labels) = fashion_mnist.load_data()

In [4]:
train_images.shape

(60000, 28, 28)

In [5]:
len(train_labels)

60000

In [6]:
np.unique(train_labels)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)

In [7]:
test_images.shape

(10000, 28, 28)

In [8]:
len(test_labels)

10000

In [9]:
test_labels

array([9, 2, 1, ..., 8, 1, 5], dtype=uint8)

In [10]:
train_images = train_images / 255.0

test_images = test_images / 255.0

In [11]:
model = keras.Sequential([
    keras.layers.Flatten(input_shape=(28, 28)),
    keras.layers.Dense(128, activation=tf.nn.relu),
    keras.layers.Dense(10, activation=tf.nn.softmax)
])
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten (Flatten)            (None, 784)               0         
_________________________________________________________________
dense (Dense)                (None, 128)               100480    
_________________________________________________________________
dense_1 (Dense)              (None, 10)                1290      
Total params: 101,770
Trainable params: 101,770
Non-trainable params: 0
_________________________________________________________________


In [12]:
model.compile(optimizer='adam', 
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [13]:
model.fit(train_images, train_labels, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.4997 - accuracy: 0.8235
Epoch 2/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.3736 - accuracy: 0.8636
Epoch 3/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.3349 - accuracy: 0.8789
Epoch 4/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.3116 - accuracy: 0.8866
Epoch 5/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.2955 - accuracy: 0.8904


In [14]:
test_loss, test_acc = model.evaluate(test_images, test_labels)

print('Test accuracy:', test_acc)

313/313 [==============================] - 1s 3ms/step - loss: 0.3360 - accuracy: 0.8805
Test accuracy: 0.8805000185966492


In [15]:
predictions = model.predict(test_images)

In [16]:
predictions[0]

array([4.8111171e-05, 8.1745861e-07, 4.8611810e-07, 5.7927785e-08,
       4.0993323e-06, 5.7367822e-03, 1.9532988e-06, 5.7112135e-02,
       4.3116542e-04, 9.3666440e-01], dtype=float32)

In [17]:
np.argmax(predictions[0])

9

In [18]:
test_labels[0]

9

In [19]:
img = test_images[0]

print(img.shape)

(28, 28)


In [20]:
img = (np.expand_dims(img,0))

print(img.shape)

(1, 28, 28)


In [21]:
predictions_single = model.predict(img)

print(predictions_single)

[[4.8111178e-05 8.1745873e-07 4.8611770e-07 5.7927792e-08 4.0993286e-06
  5.7367804e-03 1.9532990e-06 5.7112072e-02 4.3116466e-04 9.3666452e-01]]


In [22]:
np.argmax(predictions_single[0])

9